/*
 * Open-source default configuration for the Lucky Draw Wheel.
 *
 * Any field here can be overridden locally by creating config/local-config.js
 * (gitignored). When the page boots, the two files are merged so local values
 * take precedence. See config/local-config.example.js for the override shape.
 *
 *  - activityTitle : string    - main page title and <title> prefix
 *  - defaultLanguage : string  - default UI language key, e.g. "en" or "zh"
 *  - defaultTheme  : string    - one of the IDs in themeCatalog (index.html)
 *  - schemes       : string[]  - one proposal per entry
 *  - names         : string[]  - one candidate per entry (5-200 supported)
 *  - uiText        : object    - language packs, e.g. { en: {...}, zh: {...} }
 *
 * The defaults below use neutral English demo data so the open-source build
 * never ships personal or company-specific content.
 */

window.LUCKY_WHEEL_DEFAULT_CONFIG = {
  activityTitle: "Lucky Draw",
  defaultLanguage: "en",
  defaultTheme: "default",
  schemes: [
    "Proposal A",
    "Proposal B"
  ],
  names: [
    "Alice",
    "Bob",
    "Carol",
    "Dan",
    "Erin",
    "Frank",
    "Grace",
    "Heidi"
  ],
  uiText: {
    en: {
      pageTitleSuffix: "Lucky Draw Wheel",
      statsTotal: "Total",
      statsRemaining: "Remaining",
      statsDrawn: "Drawn",
      wheelAriaLabel: "Lucky draw wheel",
      hubStart: "START\nDRAW",
      hubDrawing: "Drawing...",
      statusReady: "Ready",
      statusSelected: "Selected",
      statusCompleted: "Done",
      configOpen: "Settings",
      configClose: "Close",
      configOpenAria: "Open settings panel",
      configCloseAria: "Close settings panel",
      languageSectionTitle: "Language",
      languageSectionHint: "Switch interface language",
      activitySectionTitle: "Event",
      activitySectionHint: "Set the main title",
      themeSectionTitle: "Theme",
      themeSectionHint: "Choose a visual style",
      themeReset: "Reset to Default Theme",
      themeResetMessage: "Default theme restored.",
      themeSwitchedPrefix: "Theme switched: ",
      themeImageMissingPrefix: "Missing theme image: ",
      themeImageMissingSuffix: ". Put the image in assets/themes and refresh.",
      schemeSectionTitle: "Proposals",
      schemeSectionHint: "One proposal per line; one proposal hides the outer ring",
      namesSectionTitle: "Candidates",
      namesSectionHint: "One name per line, 5-200 entries",
      drawnSectionTitle: "Drawn",
      drawnWaiting: "Waiting",
      drawnCompletedPrefix: "",
      drawnCompletedSuffix: "drawn",
      drawnEmpty: "No winners yet",
      historySectionTitle: "History",
      historySectionHint: "Live draw records",
      historyEmpty: "No history yet",
      toolsSectionTitle: "Import & Tips",
      toolsSectionHint: "Keyboard shortcuts and candidate import",
      shortcutHint: "Shortcuts: Space to draw, R to reset.",
      generateButton: "Build Wheel",
      startButton: "Start Draw",
      resetButton: "Reset All",
      fullscreenButton: "Fullscreen",
      exitFullscreenButton: "Exit Fullscreen",
      exportButton: "Export CSV",
      shuffleButton: "Shuffle List",
      clearButton: "Clear List",
      winnerKicker: "Draw Result",
      winnerTitle: "Selected",
      winnerPlaceholder: "Winner",
      winnerSchemePrefix: "Proposal: ",
      winnerMessage: "You are up next.",
      winnerContinueButton: "Continue",
      speechPrefix: "Congratulations ",
      multipleSchemesSuffix: "proposals ready",
      generatedPrefix: "Built",
      generatedNamesSuffix: "candidates",
      generatedSchemesJoin: "and",
      generatedSchemesSuffix: "proposals",
      resetDone: "All draw history has been reset.",
      shuffleDone: "Candidate list shuffled and rebuilt.",
      clearDone: "Candidate list cleared.",
      exportEmpty: "No draw results to export.",
      exportDone: "Draw results exported.",
      noRemaining: "Everyone has been drawn. Reset to play again.",
      invalidLanding: "Invalid landing. Re-drawing automatically.",
      winMessageSuffix: "is selected.",
      validationMinNames: "Add at least 5 candidates.",
      validationMaxNames: "Up to 200 candidates are supported.",
      validationMinSchemes: "Add at least 1 proposal.",
      validationMaxSchemes: "Up to 200 proposals are supported.",
      emptyWheelTitle: "Build the wheel first",
      emptyWheelHint: "One candidate per line",
      fullscreenBlocked: "Fullscreen was blocked by the browser.",
      excelNotSupported: "Excel parsing is not bundled. Save as CSV, or paste the names directly.",
      importedCountTemplate: "Imported {count} candidates.",
      fileReadFailed: "File read failed. Please paste the names instead."
    },
    zh: {
      pageTitleSuffix: "抽签大转盘",
      statsTotal: "总人数",
      statsRemaining: "剩余人数",
      statsDrawn: "已抽中",
      wheelAriaLabel: "幸运转盘",
      hubStart: "开始\n抽签",
      hubDrawing: "抽签中...",
      statusReady: "待抽签",
      statusSelected: "已抽中",
      statusCompleted: "已完成",
      configOpen: "配置",
      configClose: "收起",
      configOpenAria: "打开配置面板",
      configCloseAria: "收起配置面板",
      languageSectionTitle: "界面语言",
      languageSectionHint: "切换页面显示语言",
      activitySectionTitle: "活动配置",
      activitySectionHint: "配置页面主标题",
      themeSectionTitle: "主题背景",
      themeSectionHint: "点击缩略图切换主题",
      themeReset: "恢复默认主题",
      themeResetMessage: "已恢复默认主题。",
      themeSwitchedPrefix: "已切换主题背景：",
      themeImageMissingPrefix: "未找到主题图片：",
      themeImageMissingSuffix: "。请把图片放入 assets/themes 后刷新。",
      schemeSectionTitle: "方案配置",
      schemeSectionHint: "每行一个方案，1 个方案时隐藏外圈",
      namesSectionTitle: "候选人名单",
      namesSectionHint: "每行一个名字，5~200 人",
      drawnSectionTitle: "已抽中人员",
      drawnWaiting: "等待开始",
      drawnCompletedPrefix: "已完成",
      drawnCompletedSuffix: "人",
      drawnEmpty: "暂无抽中人员",
      historySectionTitle: "抽签历史记录",
      historySectionHint: "实时记录",
      historyEmpty: "暂无历史记录",
      toolsSectionTitle: "导入与提示",
      toolsSectionHint: "快捷键和名单文件导入",
      shortcutHint: "快捷键：空格开始抽签，R 重置。",
      generateButton: "生成转盘",
      startButton: "开始抽签",
      resetButton: "重置全部",
      fullscreenButton: "全屏模式",
      exitFullscreenButton: "退出全屏",
      exportButton: "导出结果 CSV",
      shuffleButton: "随机打乱名单",
      clearButton: "清空名单",
      winnerKicker: "抽签结果",
      winnerTitle: "荣耀揭晓",
      winnerPlaceholder: "XXX",
      winnerSchemePrefix: "讲解方案：",
      winnerMessage: "获得本次讲解机会！",
      winnerContinueButton: "继续抽签",
      speechPrefix: "恭喜",
      multipleSchemesSuffix: "个方案随机匹配",
      generatedPrefix: "已生成",
      generatedNamesSuffix: "位候选人",
      generatedSchemesJoin: "和",
      generatedSchemesSuffix: "个方案",
      resetDone: "已重置全部抽签记录。",
      shuffleDone: "名单已随机打乱并重新生成转盘。",
      clearDone: "名单已清空。",
      exportEmpty: "暂无抽签结果可导出。",
      exportDone: "已导出抽签结果 CSV。",
      noRemaining: "所有人员都已抽中过，请先重置全部。",
      invalidLanding: "本次落点异常，已自动重新抽取。",
      winMessageSuffix: "讲解机会！",
      validationMinNames: "名单至少需要 5 人。",
      validationMaxNames: "名单最多支持 200 人。",
      validationMinSchemes: "请至少配置 1 个方案。",
      validationMaxSchemes: "方案最多支持 200 个。",
      emptyWheelTitle: "请先生成转盘",
      emptyWheelHint: "每行一个名字",
      fullscreenBlocked: "当前浏览器未允许进入全屏模式。",
      excelNotSupported: "离线单文件版不内置 Excel 解析库。请在 Excel 中另存为 CSV 后导入，或直接复制粘贴名单。",
      importedCountTemplate: "已导入 {count} 人。",
      fileReadFailed: "文件读取失败，请改为复制粘贴名单。"
    }
  }
};
