/*
 * Open-source default configuration for the Lucky Draw Wheel.
 *
 * Any field here can be overridden locally by creating config/local-config.js
 * (gitignored). When the page boots, the two files are merged so local values
 * take precedence. See config/local-config.example.js for the override shape.
 *
 *  - activityTitle : string    - main page title and <title> prefix
 *  - defaultLanguage : string  - default UI language key, e.g. "en" or "zh"
 *  - defaultTheme  : string    - one of the IDs in themes
 *  - themes        : object[]  - background images and complete color skins
 *  - schemes       : string[]  - one proposal per entry
 *  - names         : string[]  - one candidate per entry (5-200 supported)
 *  - uiText        : object    - language packs, e.g. { en: {...}, zh: {...} }
 *
 * The defaults below use neutral English demo data so the open-source build
 * never ships personal or company-specific content.
 */

window.LUCKY_WHEEL_DEFAULT_CONFIG = {
  activityTitle: "Lucky Draw",
  defaultLanguage: "en",
  defaultTheme: "default",
  themes: [
    {
      id: "default",
      name: "Default Stage",
      url: null,
      skin: {
        bgDeep: "#061B4D",
        bgMid: "#081F57",
        primary: "#1F6FFF",
        neon: "#4AA8FF",
        white: "#EAF4FF",
        accent: "#FFD86B",
        accentStrong: "#FFB800",
        danger: "#FF477E",
        panelRgb: "6, 27, 77",
        primaryRgb: "31, 111, 255",
        neonRgb: "74, 168, 255",
        accentRgb: "255, 216, 107",
        palette: ["#0A47FF", "#1F6FFF", "#4AA8FF", "#123D9D", "#0D2B75", "#2A7BFF", "#6BBEFF", "#FFD86B", "#FFB800", "#EAF4FF"]
      }
    },
    {
      id: "black-gold-pk-stage",
      name: "Black Gold Stage",
      url: "assets/themes/black-gold-pk-stage.png",
      skin: {
        bgDeep: "#030303",
        bgMid: "#14100A",
        primary: "#B77A20",
        neon: "#F7D27A",
        white: "#FFF8DF",
        accent: "#F7D27A",
        accentStrong: "#B77A20",
        danger: "#8F1F2C",
        panelRgb: "8, 7, 5",
        primaryRgb: "183, 122, 32",
        neonRgb: "247, 210, 122",
        accentRgb: "247, 210, 122",
        palette: ["#F7D27A", "#16110A", "#B77A20", "#FFF2B8", "#3A2811", "#D6A743", "#080705", "#C89135", "#F3C96A", "#21170B"]
      }
    },
    {
      id: "smart-parking-pk-arena",
      name: "Smart Arena",
      url: "assets/themes/smart-parking-pk-arena.png",
      skin: {
        bgDeep: "#041A28",
        bgMid: "#063A55",
        primary: "#00B8FF",
        neon: "#38F2D5",
        white: "#E9FFFB",
        accent: "#FFD86B",
        accentStrong: "#FFB800",
        danger: "#FF4D7D",
        panelRgb: "4, 26, 40",
        primaryRgb: "0, 184, 255",
        neonRgb: "56, 242, 213",
        accentRgb: "255, 216, 107",
        palette: ["#00B8FF", "#38F2D5", "#0A6CFF", "#063A55", "#0BD3A3", "#76FFF0", "#FFD86B", "#0E829A", "#E9FFFB", "#0B4F73"]
      }
    },
    {
      id: "gold-presentation-duel",
      name: "Golden Duel",
      url: "assets/themes/gold-presentation-duel.png",
      skin: {
        bgDeep: "#120B03",
        bgMid: "#2B1805",
        primary: "#D58B1F",
        neon: "#FFE08A",
        white: "#FFF9E6",
        accent: "#FFD86B",
        accentStrong: "#FFB800",
        danger: "#C83D2F",
        panelRgb: "26, 14, 4",
        primaryRgb: "213, 139, 31",
        neonRgb: "255, 224, 138",
        accentRgb: "255, 216, 107",
        palette: ["#FFD86B", "#FFB800", "#8A5314", "#FFF2B5", "#2B1805", "#D58B1F", "#6C3E0D", "#FFE08A", "#B87318", "#FFF9E6"]
      }
    },
    {
      id: "blue-tech-pk-stage",
      name: "Blue Tech Stage",
      url: "assets/themes/blue-tech-pk-stage.png",
      skin: {
        bgDeep: "#061B4D",
        bgMid: "#081F57",
        primary: "#1F6FFF",
        neon: "#4AA8FF",
        white: "#EAF4FF",
        accent: "#FFD86B",
        accentStrong: "#FFB800",
        danger: "#FF477E",
        panelRgb: "6, 27, 77",
        primaryRgb: "31, 111, 255",
        neonRgb: "74, 168, 255",
        accentRgb: "255, 216, 107",
        palette: ["#0A47FF", "#1F6FFF", "#4AA8FF", "#123D9D", "#0D2B75", "#2A7BFF", "#6BBEFF", "#FFD86B", "#FFB800", "#EAF4FF"]
      }
    },
    {
      id: "ai-traffic",
      name: "AI Traffic",
      url: "assets/themes/ai-traffic.png",
      skin: {
        bgDeep: "#020B1C",
        bgMid: "#071D42",
        primary: "#087BFF",
        neon: "#20BBFF",
        white: "#F4F8FF",
        accent: "#F2C66D",
        accentStrong: "#D99A2B",
        danger: "#FF476F",
        panelRgb: "2, 11, 28",
        primaryRgb: "8, 123, 255",
        neonRgb: "32, 187, 255",
        accentRgb: "242, 198, 109",
        palette: ["#087BFF", "#20BBFF", "#0A47D9", "#F2C66D", "#D99A2B", "#071D42", "#5ED7FF", "#FFF1C7", "#114E9E", "#F4F8FF"]
      }
    },
    {
      id: "mecha-pk-battle",
      name: "Mecha Battle",
      url: "assets/themes/mecha-pk-battle.png",
      skin: {
        bgDeep: "#090B14",
        bgMid: "#18213A",
        primary: "#2E6BFF",
        neon: "#00E5FF",
        white: "#F0F7FF",
        accent: "#FF4D5E",
        accentStrong: "#FFB800",
        danger: "#FF2D55",
        panelRgb: "9, 11, 20",
        primaryRgb: "46, 107, 255",
        neonRgb: "0, 229, 255",
        accentRgb: "255, 77, 94",
        palette: ["#2E6BFF", "#00E5FF", "#18213A", "#FF4D5E", "#F0F7FF", "#5C7CFA", "#111827", "#FFB800", "#0EA5E9", "#334155"]
      }
    }
  ],
  schemes: [
    "Proposal A",
    "Proposal B"
  ],
  names: [
    "Alice",
    "Bob",
    "Carol",
    "Dan",
    "Erin",
    "Frank",
    "Grace",
    "Heidi"
  ],
  uiText: {
    en: {
      pageTitleSuffix: "Lucky Draw Wheel",
      statsTotal: "Total",
      statsRemaining: "Remaining",
      statsDrawn: "Drawn",
      wheelAriaLabel: "Lucky draw wheel",
      hubStart: "START\nDRAW",
      hubDrawing: "Drawing...",
      statusReady: "Ready",
      statusSelected: "Selected",
      statusCompleted: "Done",
      configOpen: "Settings",
      configClose: "Close",
      configOpenAria: "Open settings panel",
      configCloseAria: "Close settings panel",
      languageSectionTitle: "Language",
      languageSectionHint: "Switch interface language",
      activitySectionTitle: "Event",
      activitySectionHint: "Set the main title",
      themeSectionTitle: "Theme",
      themeSectionHint: "Choose a visual style",
      themeReset: "Reset to Default Theme",
      themeResetMessage: "Default theme restored.",
      themeSwitchedPrefix: "Theme switched: ",
      themeImageMissingPrefix: "Missing theme image: ",
      themeImageMissingSuffix: ". Put the image in assets/themes and refresh.",
      schemeSectionTitle: "Proposals",
      schemeSectionHint: "One proposal per line; one proposal hides the outer ring",
      namesSectionTitle: "Candidates",
      namesSectionHint: "One name per line, 5-200 entries",
      drawnSectionTitle: "Drawn",
      drawnWaiting: "Waiting",
      drawnCompletedPrefix: "",
      drawnCompletedSuffix: "drawn",
      drawnEmpty: "No winners yet",
      historySectionTitle: "History",
      historySectionHint: "Live draw records",
      historyEmpty: "No history yet",
      toolsSectionTitle: "Import & Tips",
      toolsSectionHint: "Keyboard shortcuts and candidate import",
      shortcutHint: "Shortcuts: Space to draw, R to reset.",
      importHelp: "Import a .txt or .csv candidate list. One name per line, or separated by commas.",
      importExample: "Alice\nBob\nCarol\nDan\nErin",
      generateButton: "Build Wheel",
      startButton: "Start Draw",
      resetButton: "Reset All",
      fullscreenButton: "Fullscreen",
      exitFullscreenButton: "Exit Fullscreen",
      exportButton: "Export CSV",
      shuffleButton: "Shuffle List",
      clearButton: "Clear List",
      winnerKicker: "Draw Result",
      winnerTitle: "Selected",
      winnerPlaceholder: "Winner",
      winnerSchemePrefix: "Proposal: ",
      winnerMessage: "You are up next.",
      winnerContinueButton: "Continue",
      speechPrefix: "Congratulations ",
      multipleSchemesSuffix: "proposals ready",
      generatedPrefix: "Built",
      generatedNamesSuffix: "candidates",
      generatedSchemesJoin: "and",
      generatedSchemesSuffix: "proposals",
      resetDone: "All draw history has been reset.",
      shuffleDone: "Candidate list shuffled and rebuilt.",
      clearDone: "Candidate list cleared.",
      exportEmpty: "No draw results to export.",
      exportDone: "Draw results exported.",
      noRemaining: "Everyone has been drawn. Reset to play again.",
      invalidLanding: "Invalid landing. Re-drawing automatically.",
      winMessageSuffix: "is selected.",
      validationMinNames: "Add at least 5 candidates.",
      validationMaxNames: "Up to 200 candidates are supported.",
      validationMinSchemes: "Add at least 1 proposal.",
      validationMaxSchemes: "Up to 200 proposals are supported.",
      emptyWheelTitle: "Build the wheel first",
      emptyWheelHint: "One candidate per line",
      fullscreenBlocked: "Fullscreen was blocked by the browser.",
      excelNotSupported: "Excel parsing is not bundled. Save as CSV, or paste the names directly.",
      importedCountTemplate: "Imported {count} candidates.",
      fileReadFailed: "File read failed. Please paste the names instead."
    },
    zh: {
      pageTitleSuffix: "抽签大转盘",
      statsTotal: "总人数",
      statsRemaining: "剩余人数",
      statsDrawn: "已抽中",
      wheelAriaLabel: "幸运转盘",
      hubStart: "开始\n抽签",
      hubDrawing: "抽签中...",
      statusReady: "待抽签",
      statusSelected: "已抽中",
      statusCompleted: "已完成",
      configOpen: "配置",
      configClose: "收起",
      configOpenAria: "打开配置面板",
      configCloseAria: "收起配置面板",
      languageSectionTitle: "界面语言",
      languageSectionHint: "切换页面显示语言",
      activitySectionTitle: "活动配置",
      activitySectionHint: "配置页面主标题",
      themeSectionTitle: "主题背景",
      themeSectionHint: "点击缩略图切换主题",
      themeReset: "恢复默认主题",
      themeResetMessage: "已恢复默认主题。",
      themeSwitchedPrefix: "已切换主题背景：",
      themeImageMissingPrefix: "未找到主题图片：",
      themeImageMissingSuffix: "。请把图片放入 assets/themes 后刷新。",
      schemeSectionTitle: "方案配置",
      schemeSectionHint: "每行一个方案，1 个方案时隐藏外圈",
      namesSectionTitle: "候选人名单",
      namesSectionHint: "每行一个名字，5~200 人",
      drawnSectionTitle: "已抽中人员",
      drawnWaiting: "等待开始",
      drawnCompletedPrefix: "已完成",
      drawnCompletedSuffix: "人",
      drawnEmpty: "暂无抽中人员",
      historySectionTitle: "抽签历史记录",
      historySectionHint: "实时记录",
      historyEmpty: "暂无历史记录",
      toolsSectionTitle: "导入与提示",
      toolsSectionHint: "快捷键和名单文件导入",
      shortcutHint: "快捷键：空格开始抽签，R 重置。",
      importHelp: "导入 .txt 或 .csv 候选人名单。可以每行一个名字，也可以用逗号分隔。",
      importExample: "张三\n李四\n王五\n赵六\n钱七",
      generateButton: "生成转盘",
      startButton: "开始抽签",
      resetButton: "重置全部",
      fullscreenButton: "全屏模式",
      exitFullscreenButton: "退出全屏",
      exportButton: "导出结果 CSV",
      shuffleButton: "随机打乱名单",
      clearButton: "清空名单",
      winnerKicker: "抽签结果",
      winnerTitle: "荣耀揭晓",
      winnerPlaceholder: "XXX",
      winnerSchemePrefix: "讲解方案：",
      winnerMessage: "获得本次讲解机会！",
      winnerContinueButton: "继续抽签",
      speechPrefix: "恭喜",
      multipleSchemesSuffix: "个方案随机匹配",
      generatedPrefix: "已生成",
      generatedNamesSuffix: "位候选人",
      generatedSchemesJoin: "和",
      generatedSchemesSuffix: "个方案",
      resetDone: "已重置全部抽签记录。",
      shuffleDone: "名单已随机打乱并重新生成转盘。",
      clearDone: "名单已清空。",
      exportEmpty: "暂无抽签结果可导出。",
      exportDone: "已导出抽签结果 CSV。",
      noRemaining: "所有人员都已抽中过，请先重置全部。",
      invalidLanding: "本次落点异常，已自动重新抽取。",
      winMessageSuffix: "讲解机会！",
      validationMinNames: "名单至少需要 5 人。",
      validationMaxNames: "名单最多支持 200 人。",
      validationMinSchemes: "请至少配置 1 个方案。",
      validationMaxSchemes: "方案最多支持 200 个。",
      emptyWheelTitle: "请先生成转盘",
      emptyWheelHint: "每行一个名字",
      fullscreenBlocked: "当前浏览器未允许进入全屏模式。",
      excelNotSupported: "离线单文件版不内置 Excel 解析库。请在 Excel 中另存为 CSV 后导入，或直接复制粘贴名单。",
      importedCountTemplate: "已导入 {count} 人。",
      fileReadFailed: "文件读取失败，请改为复制粘贴名单。"
    }
  }
};
